/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import base.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @authors Jorge & Daniel
 */
public class Home extends javax.swing.JPanel {

    private List<Word> words;   //Indice Invertido
    private List<AddressDoc> docs;  //Documentos
    private int numberIds;  //Id
    
    /**
     * Creates new form Homes
     */
    public Home() {
        this.words = new ArrayList<>();
        this.docs = new ArrayList<>();
        numberIds = 1;
        initComponents();
    }
    
    public Home(int numberIds, List<Word> words, List<AddressDoc> docs) {
        this.numberIds = numberIds;
        this.words = words;
        this.docs = docs;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagem = new javax.swing.JLabel();
        bttList = new javax.swing.JButton();
        bttSearch = new javax.swing.JButton();
        bttReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttAddDoc = new javax.swing.JButton();

        imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/outros/busca-conteudo.jpg"))); // NOI18N

        bttList.setText("Listar");
        bttList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListActionPerformed(evt);
            }
        });

        bttSearch.setText("Buscar");
        bttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSearchActionPerformed(evt);
            }
        });

        bttReset.setText("Resetar");
        bttReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttResetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        jLabel1.setToolTipText("");

        bttAddDoc.setText("Adicionar Documento");
        bttAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttAddDoc)
                        .addGap(33, 33, 33)
                        .addComponent(bttList, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(bttReset, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttList)
                            .addComponent(bttSearch)
                            .addComponent(bttAddDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddDocActionPerformed
        Main.janela.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new DocumentFeeder(numberIds,words,docs));  //Chama a janela de adicionar passando o id, indice invertido, documentos
        Main.janela.setSize(620, 360);
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttAddDocActionPerformed

    private void bttListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListActionPerformed
        Main.janela.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new DocumentList(this.numberIds,this.words,this.docs)); //Chama a janela de listar passando o id, indice invertido, documentos
        Main.janela.setSize(430, 370);
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttListActionPerformed

    private void bttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSearchActionPerformed
        Main.janela.setVisible(false);
        Main.janela.remove(this);
        Main.janela.add(new Search(this.numberIds,this.words,this.docs));   //Chama a janela de busca passando o id, indice invertido, documentos
        Main.janela.setSize(430, 360);
        Main.janela.setVisible(true);
    }//GEN-LAST:event_bttSearchActionPerformed

    private void bttResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttResetActionPerformed
        this.numberIds = 1; //Reseta id
        this.words = new ArrayList<>(); //Reseta palavras
        this.docs = new ArrayList<>();  //Reseta documentos
    }//GEN-LAST:event_bttResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddDoc;
    private javax.swing.JButton bttList;
    private javax.swing.JButton bttReset;
    private javax.swing.JButton bttSearch;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
